source 'https://github.com/WyICSP/WFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '9.0'
inhibit_all_warnings!                         #去除警告

target 'WFKitLogin_Example' do
  pod 'WFKitLogin', :path => '../'

  target 'WFKitLogin_Tests' do
    inherit! :search_paths

    
  end
end
